redhat-openshift-ecosystem/opct

manifests/openshift-conformance-validated.yaml
manifests/openshift-kube-conformance.yaml
pkg/assets/bindata.go
pkg/run/run.go

We are using `stable` version of the plugin image to avoid disruptions when many engineers are testing different components on the certificate system.

feat(plugin-stable): switch to stable version to avoid disruptions

---

manifests/openshift-conformance-validated.yaml
manifests/openshift-kube-conformance.yaml
pkg/assets/bindata.go

Add shared volume to avoid mixing internal files (kubeconfig, aggregator status file, openshift-tests utility, openshift-tests stat file, etc) to non-related with sonobuoy results, but being used in the SONOBUOY_RESULT_DIR
Ref https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/13

chore(plugin-manifest): add shared volume

---

.github/workflows/go.yaml
manifests/openshift-conformance-validated.yaml
manifests/openshift-kube-conformance.yaml
pkg/assets/bindata.go

This PR will track moving code from the mvp to main branch. A few notes on the changes...
- Updating `SourceURL` should not make any functional changes to the manifests. ([source](https://github.com/vmware-tanzu/sonobuoy/blob/main/pkg/plugin/manifest/manifest.go#L49-L51))

chore(promote): renaming mvp -> main

---

.gitignore
pkg/version/version.go

The leading `v` will be included in tag name already.

chore(version): remove leading v from version output

---

README.md

If you don't click into `docs/`, it appears as though we don't have any docs. 
Also, removing the help file output as I'm not sure its adding anything besides fluff :)

Link to guides from readme and remove help file

---

docs/user.md

User documentation to provide a way to send the results to Red Hat team.
Waiting for the definition of the initial steps.
https://issues.redhat.com/browse/SPLAT-724

doc/user: add temporary submit results steps

---

go.mod
go.sum
pkg/run/run.go
pkg/types.go

Store production versions in ConfigMap `openshift-provider-certification-version`.
Also, bump sonobuoy version to v0.56.10 so we can utilize optional preflight tests.

SPLAT-643: Store production versions in ConfigMap.

---

docs/user.md

Keeping the `dedicated` RAM requirement for compute pool in sync with the regular environment to run certification tests.
/assign @bostrt

fix/doc: Compute pool should be always 16 GiB

---

pkg/status/printer.go

As the number of plugins will grow (upgrade, artifacts collector), this change will allow more space on the status table to fit new names:
~~~
Wed, 09 Nov 2022 13:29:17 -03> Global Status: running
JOB_NAME                           | STATUS     | RESULTS    | PROGRESS                  | MESSAGE
01-openshift-cluster-upgrade       | running    |            | 0/0 (0 failures)          | status=Working towards 4.11.12: 640 of 803 done (79% complete), waiting on service-ca
10-openshift-kube-conformance      | running    |            | 0/352 (0 failures)        | status=waiting-for=01-openshift-cluster-upgrade=(0/0/0)=[99/100]
20-openshift-conformance-validated | running    |            | 0/3487 (0 failures)       | status=blocked-by=10-openshift-kube-conformance=(0/-352/0)=[0/100] …

chore/printer: update space to allow new plugin names

---

manifests/openshift-conformance-validated.yaml
manifests/openshift-kube-conformance.yaml
pkg/assets/bindata.go

Rename the plugin to reflect the order of execution.
https://issues.redhat.com/browse/SPLAT-869
Relates to: 
- https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/30
- https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/21

SPLAT-869 - chore/manifests: rename plugins to be ordered by execution

---

docs/README.md
docs/dev.md
docs/support-guide.md
docs/troubleshooting-guide.md
docs/user-installation-checklist.md
docs/user-installation-review.md
docs/user.md
mkdocs.yml

Documentation targeting to update the OPCT guides with inputs from the Provider Review.
Related cards:
- Document filters: https://issues.redhat.com/browse/SPLAT-831
- Create Support Guide: https://issues.redhat.com/browse/SPLAT-832
- Create Cluster Review Guide: https://issues.redhat.com/browse/SPLAT-833
Indirect related (mentioned on the documentation):
- `process` command: https://issues.redhat.com/browse/SPLAT-834

SPLAT-811 - Documentation updates related to the Provider Review

---

pkg/run/run.go

Change `--dedicated` to default true. 
Wait for https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/23 to merge and then address documentation.

SPLAT-850: Use dedicated mode by default

---

manifests/openshift-artifacts-collector.yaml
manifests/openshift-conformance-validated.yaml
pkg/assets/bindata.go

Introduce to plugin artifacts collector, to collect:
- e2e suite list for openshift and kubernetes conformance
- must-gather
https://issues.redhat.com/browse/SPLAT-868
Depends:
- https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/23

SPLAT-868 - plugin: add artifacts collector instance for openshift-tests

---

manifests/openshift-artifacts-collector.yaml
manifests/openshift-conformance-validated.yaml
manifests/openshift-kube-conformance.yaml
pkg/assets/bindata.go

This PR bumps the openshift-tests plugin to v0.2.1, covered by this[1] PR, fixing the regression introduced on v0.2.0. More details on PR and related Jira card.
Once this PR is merged, we need to create a CLI release v0.2.1.
[1] https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/28

SPLAT-909: fix update plugin tag to fix regressions

---

pkg/destroy/destroy.go
pkg/run/run.go
pkg/types.go

https://issues.redhat.com/browse/OPCT-6
This PR creates custom permissions to be used on Sonobuoy's service accounts.
The default sonobuoy's permissions are crashing the cluster upgrade feature (implemented on #33), described on OPCT-6. The goal is to avoid using system groups to not fall into pod admissions security admissions introduced on kube 1.24 (4.11).
The groups `system:authenticated` and `system:serviceaccounts` previously used were crashing the upgrade. Ref [KCS 5875621](https://access.redhat.com/solutions/5875621)
```
$ oc adm policy who-can use scc anyuid | grep serviceaccounts
system:serviceaccounts 
```
Tests checklist:

OPCT-6 - fix/rbac: manage custom ServiceAccount and roles

---

docs/support-guide.md

This documentation will act as a stop-gap until we merge the automated upgrade code. After the merge, we'll probably have to rewrite some of these docs.

docs: add stop-gap docs for upgrade review

---

pkg/types.go

The goal of this PR is to provide the correct privileges to the namespace created to OPCT environment. The following warnings from PSA was introduced OCP 4.11:
```
$ KUBECONFIG=$PWD/.opct-41124/clusters/opct-41124/auth/kubeconfig oc logs sonobuoy -n openshift-provider-certification |grep 'would violate PodSecurity'
W0119 13:10:17.291197       1 warnings.go:70] would violate PodSecurity "restricted:latest": 
allowPrivilegeEscalation != false (containers "report-progress", "plugin", "sonobuoy-worker" must set securityContext.allowPrivilegeEscalation=false), 
unrestricted capabilities (containers "report-progress", "plugin", "sonobuoy-worker" must set securityContext.capabilities.drop=["ALL"]), 
runAsNonRoot != true (pod or containers "report-progress", "plugin", "sonobuoy-worker" must set …
```

OPCT-11 - fix/psa-warn: apply NS labels for PSA Level privileged

---

manifests/openshift-conformance-validated.yaml
manifests/openshift-kube-conformance.yaml
pkg/assets/bindata.go
pkg/run/run.go
pkg/types.go

Intro to dev flag to allow developers fastly use the "e2e limit", feature of Plugins, when running a development environment.
To use the DEV_MODE env var on plugins, we need to change the plugins manifests and rebuild the CLI. It is very useful when I am trying other features on CLI or plugins, to make sure the complete flow is running, but with a small set of e2e (sometimes we don't need to check the e2e results, we want to know the flow will work).
But it's kinda boring to change the manifests every time and rebuild the CLI, it could be more useful when setting a CLI flag to run in "DEV MODE".
The quick implementation was done when running the upgrade feature, but a final change needs a more understanding of the impact of allowing this by default. …

OPCT-32 - Dev env: enable dev-count flag to limit e2e list in runtime

---

docs/user.md
go.mod
manifests/openshift-artifacts-collector.yaml
manifests/openshift-cluster-upgrade.yaml
manifests/openshift-conformance-validated.yaml
manifests/openshift-kube-conformance.yaml
pkg/assets/bindata.go
pkg/run/run.go

https://issues.redhat.com/browse/SPLAT-651
Support upgrade conformance.
- Introduces new flags to control whether the execution needs to run the upgrade cluster or not:
- `--mode=upgrade`
- `--upgrade-to-image=<release_digest>` (`$(oc adm release info 4.Y+1.Z -o jsonpath={.image}`)
- Create config map with plugin variables (the sonobuoy native feature wipes all existing from `podSpec` which is undesired)
- add a new plugin instance of openshift-tests to run upgrades: `05-openshift-cluster-upgrade`
Blocked by:
Blocked by Plugin release:
Checklist:
Tests checklist:

OPCT-5: support upgrade execution mode

---

.github/workflows/static-website.yml
mkdocs.yml

Initial setup to create a mkdocs website build to publish a documentation page into Github Pages: https://redhat-openshift-ecosystem.github.io/provider-certification-tool

OPCT-36: Documentation - create static website with GHPages

---

manifests/openshift-artifacts-collector.yaml
manifests/openshift-conformance-validated.yaml
manifests/openshift-kube-conformance.yaml
pkg/assets/bindata.go

Back port plugin changes:
- https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/33
- https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/32
https://issues.redhat.com/browse/SPLAT-646

bump plugin image to v0.2.2

---

manifests/openshift-artifacts-collector.yaml
manifests/openshift-cluster-upgrade.yaml
manifests/openshift-conformance-validated.yaml
manifests/openshift-kube-conformance.yaml
pkg/assets/bindata.go

https://issues.redhat.com/browse/OPCT-11
Bump to v0.3.0-alpha1 after plugin fix https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/34
This PR will improve the counters when running OPCT, fixing a bug on openshift-tests on 4.12+ clusters.
We don't need to create a alpha release for CLI, but having this change on the master will get newer results from OpenShift CI, running weekly for 4.12.

OPCT-11: fix counters on plugin report progress

---

manifests/openshift-artifacts-collector.yaml
manifests/openshift-cluster-upgrade.yaml
manifests/openshift-conformance-validated.yaml
manifests/openshift-kube-conformance.yaml
pkg/assets/bindata.go

Bump to the v0.3.0 release.
https://issues.redhat.com/browse/OPCT-4
Blocked by:

OPCT-4: bump to release v0.3.0

---

docs/user-installation-disconnected.md
docs/user.md
manifests/openshift-artifacts-collector.yaml
manifests/openshift-cluster-upgrade.yaml
manifests/openshift-conformance-validated.yaml
manifests/openshift-kube-conformance.yaml
mkdocs.yml
pkg/assets/bindata.go
pkg/run/run.go
pkg/types.go

Introduces a new argument to the `run` command called `--image-repository` .  When provided the `--image-repository`  argument, the tool will look to the provided registry as the source of images.

OPCT-28: Support Disconnected Mirror Registry

---

.github/workflows/release.yaml
Makefile
docs/dev.md
hack/Containerfile
hack/Containerfile.ci

https://issues.redhat.com/browse/OPCT-191
This PR introduces the CLI container image, publishing it on Quay.io to allow be mirrored by OpenShift CI jobs (https://github.com/openshift/release/pull/37955), decreasing the complexity and logic of the CI steps.
https://quay.io/repository/ocp-cert/opct?tab=tags

OPCT-191: Build and publish the CLI image to registry

---

.github/workflows/changelog-configuration.json
.github/workflows/release.yaml

https://issues.redhat.com/browse/OPCT-192
The goal of this card is to automatically create the changelog based on the commit standards.
The labels should be defined to fit OPCT project. The existing is suggested, it would be nice to be adapted for the same used by OCP projects

OPCT-192: Automatically create changelog based on the tags

---

pkg/report/cmd.go

https://issues.redhat.com/browse/OPCT-180
The plugin must not pass on `report` when the runtime reported failures.
The runtime fails creating a 'fake' JUnit with failed reason. When there is only one failed test, the plugin evaluation must consider it and ignore any filter.

OPCT-180: Fix report when plugin is failing on runtime

---

Makefile
hack/Containerfile
hack/Containerfile.ci

Removing dependency on OCP CI registry images (`registry.ci.openshift.org`) when building the project introduced on https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/51 . It would be nice to unblock external contributors to use the tool when need to build it locally.
We don't expect to fall into Docker limitations as that image should be used in a developer environment. 
https://issues.redhat.com/browse/OPCT-191
```
$ make linux-amd64-container 
podman build -t quay.io/ocp-cert/opct:latest -f hack/Containerfile --build-arg=RELEASE_TAG=0.0.0 .
[1/2] STEP 1/5: FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.13 AS builder
Trying to pull registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.13...
Error: error creating build …
```

OPCT-191: Removing OCP CI image dependency on build layer

---

docs/user-installation-review.md

https://issues.redhat.com/browse/OPCT-12
Improving the documentation for 'installation review', providing references of expected etcd performance when inspecting the etcd logs for slow requests on must-gather.
Sync with https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/40

OPCT-12: Review docs for tool to parsing etcd logs

---

.github/workflows/go.yaml
hack/patches/pkg-assets-bindata.go.patch
hack/update-generated-bindata.sh
internal/pkg/sippy/sippy.go
pkg/assets/bindata.go

The motivation of this PR is to fix/bump the static code check used on Github CI, fixing issues reported on the new version. The issue has been started, and it's isolated, from the PR https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/54
Changes:
1) bump staticcheck version
2) fix issues reported by it
StaticCheck plugin used to Code Analysis on our CI was reporting issues when bumping the OCP API lib, this is a false-positive:
- https://github.com/redhat-openshift-ecosystem/provider-certification-tool/actions/runs/4608846263/jobs/8145167561
When updating the static check version it reports `io/ioutil` deprecation addressed on this PR:
~~~
Error: internal/pkg/sippy/sippy.go:6:2: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same …

OPCT-199: Fixes related to CI code static analysis on dependencies

---

hack/Containerfile
hack/Containerfile.ci

Bump UBI to fix security issues before releasing v0.4.
References:
- https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8
- https://issues.redhat.com/browse/OPCT-209
- https://quay.io/repository/ocp-cert/opct?tab=tags
Before:
After:

OPCT-209: bump UBI to fix security issues on container

---

docs/README.md
docs/user.md
mkdocs.yml

Fixes on the User documentation and mkdocs reference for the project name fixed on https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/58

OPCT-177: Documentation fixing sections indentation and formatting 

---

manifests/openshift-artifacts-collector.yaml
manifests/openshift-cluster-upgrade.yaml
manifests/openshift-conformance-validated.yaml
manifests/openshift-kube-conformance.yaml
pkg/run/run.go

nit pre-release to prevent future confusion when reading the code on the reference of "tools" and "plugins" images.
- Tools image is the base image used to ship shared tools/binaries used by the plugin's image
- Plugins image contains the openshift-provider-cert plugin itself, it is based on the Tools image

OPCT-177: nit rename plugins image to reflect the real name

---

pkg/types.go

Bumping plugin image for v0.4.0 release.
It will be created after all PRs are merged and v0.4.0-rc/beta* has been validated.

OPCT-177: bump plugins image to release v0.4.0

---

.github/workflows/release.yaml
.gitignore
Makefile
docs/dev.md
pkg/assets/bindata.go

- Fix unbound variables on the CI step when creating release v0.4: https://github.com/redhat-openshift-ecosystem/provider-certification-tool/actions/runs/5047592402/jobs/9054669579
- Reorder the container build step to make sure it will succeed before creating the release, otherwise, the workflow should fail
- copy and ship binaries with the prefix `opct-*` (s/openshift-provider-cert/opct/) to deprecate the cert name in future releases
- update static files crashing when processing the tool with renamed argument `plugins-image` (missing on https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/66 )
- add dev doc expanding the release process with more information about manual tests

OPCT-177: pre-release v0.4.0 fixes

---

.github/workflows/go.yaml
cmd/root.go
internal/pkg/summary/consolidated.go
pkg/report/cmd.go
pkg/run/run.go
pkg/status/printer_test.go

Create CI improvements identified in https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/73 (quick win):
- Remove duplicated steps in the job
- Add linter job
- Create job chain, requiring [linter and static check] to run [tests and vet]

OPCT-199: CI - added linter job and update workflow dependencies

---

docs/review/index.md
docs/review/rules.md
mkdocs.yml

This change introduces the document used in the report enhancement in progress at https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/76 
The Rules are a set of tests with fixed acceptance criteria that will evaluate the data collected when running `report` command. To allow flexibility and increase the UX, we are only keeping in the code the "Rule ID", linking it to a "Knowledge Base" to explore why the rule is failing, and the recommended next steps.
The version of #76 is tested internally by developers but the document can be available as a dev preview when the report frontend is mounting the hyperlinks for the Rules.
The demo is available here (direct 4:40) [Red Hat only]: https://drive.google.com/file/d/1v4EIO1mXesDKKy0meZeiVcZ-kSjf7o_E/view?usp=sharing
The …

OPCT-226: Introduce knowledge document for OPCT Report Rules

---

.github/workflows/static-website.yml
.gitignore
docs/CHANGELOG.md
hack/generate-changelog.sh

Fixes #74 :
- the CHANGELOG.md is generated by CI and available only in the rendered page. If we decide to keep it versioned, we can add it in the future. For now it is generated automatically
- force CI step/action to fetch tags to run correctly the changelog generator
- nits shell script

OPCT-239: Fix CI step forcing to fetch tags to generate changelog file

---

pkg/types.go

Update base plugin image to support OCP 4.14.
This is a backport of https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/43 bumping to plugins image plugin backport https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/47 (required to be merged).
The v0.5 will cover that patch, but that release is still blocked by #76 
https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/releases/tag/v0.4.1
https://quay.io/repository/ocp-cert/openshift-tests-provider-cert?tab=tags

OPCT-213: backport plugins to support OCP 4.14 on v0.4

---

docs/review/rules.md

Introducing etcd check rules based in the parsed logs for etcd (etcd request took too long).
The acceptance values are calibrated from the baseline providers:
- AWS (ocp414rc0_AWS_None_202309222127_sonobuoy_47efe9ef-06e4-48f3-a190-4e3523ff1ae0.tar.gz)
- AWS (4.13.9-20230925-HighlyAvailable-aws-None-202309250459_sonobuoy_f4e06587-e7b3-4cbd-bcf4-d1350ec35d9a.tar.gz):
- vSphere (4.13.9-20230821-HighlyAvailable-vsphere-None.tar.gz):
The check rules is implemented in the feature https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/76 
https://github.com/redhat-openshift-ecosystem/provider-certification-tool/blob/dc2156317dfc92b47c582b494fef47876337d94b/internal/opct/report/checks.go#L321-L388

OPCT-226: Added check rules for etcd

---

pkg/retrieve/retrieve.go
pkg/run/run.go
pkg/status/status.go

The interval watching, and printing in the stdout is not customized leading to a high amount of messages in the stdout - it is good for troubleshooting purpose, but a downside is it increases the amount of logs stored in CI with actionable information.
This PR introduces a possibility to set the flag `--watch-interval=int` to the `status` command, also called by the `run` command.
This change is isolated from the `report` enhancement covered in #76

OPCT-226: cmd/status: Adding flag to set the watch interval

---

docs/user.md

Remove form the user guide the ambiguous instruction to setup dedicated node as we are requiring an agnostic installation, and providing an option to use MachineSet, but MAPI isn't available in agnostic installations/platform type None.
This option can be valid when we'll create different guides. Currently the "User Guide" is very specific for VCSP requirements. The intention of #88 is to improve it, but we don't have ETA yet.

OPCT-257: Doc - remove machineset option in dedicated node section

---

docs/user.md

Documenting the OCP topologies tested and supported by OPCT validation process.
https://issues.redhat.com/browse/OPCT-41
Topology description was based in the product docs: 
https://docs.openshift.com/container-platform/4.13/installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer.html#agent-based-installer-workflow

OPCT-41: Documenting the supported OCP topologies

---

.github/workflows/go.yaml

Introducing github step to run the `opct report` command to help validating the CLI changes.

OPCT-00: CI: add job cmd-report

---

.github/workflows/release.yaml

Fix Github action pipeline when uploading artifacts to Github release.

OPCT-257: CI pipeline fix when uploading artifacts to release

---

pkg/client/client.go
pkg/destroy/destroy.go
pkg/retrieve/retrieve.go
pkg/run/run.go
pkg/status/status.go

- Fix error handler across different parts of the code, preventing fatal when not needed, raising to CLI handle the error message/code.
- Kubeconfig env var wasn't well evaluated when using the `pkg/client/client.go` as API, adjusting to make precedence of env variable

OPCT-257: improve error handler when using the client as api pkg

---

.github/workflows/release.yaml

Mark as pre-releases the releases created by CI pipeline, instead of `Latestt`. Letting latest marked manually allowing creating many pre-releases without manual intervention

OPCT-257: CI/set prerelease flag when pipeline creates release

---

.github/workflows/release.yaml

Update to the official Quay Org which other images is already published: @opct
Changes in this repo updates the CI pipeline to publish to new Org/repo when a release is created.
Prerequisites is complete:
- repo `opct/opct` created
- robot account for this project created adding grants to that repo
- github secrets updated with new service account3
Migrating from: https://quay.io/repository/ocp-cert/opct?tab=tags
To repo: https://quay.io/repository/opct/opct

OPCT-257: CI - add service account to publish to new Quay Org

---

pkg/types.go

Bump plugins version to v0.5.0 GA
https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/actions/runs/10308276521
https://issues.redhat.com/browse/OPCT-257

OPCT-257: bump plugins to v0.5.0

---

data/templates/plugins/openshift-cluster-upgrade.yaml
data/templates/plugins/openshift-conformance-replay.yaml
data/templates/plugins/openshift-conformance-validated.yaml
data/templates/plugins/openshift-kube-conformance.yaml

This PR fixes the wrong kubernetes login URL by preventing silent failures when the service network is different than default `172.30.0.0/1` and kubernetes services will not be the URL `https://172.30.0.1:443`
Example of Prow job failing: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54722/rehearse-54722-periodic-ci-openshift-assisted-test-infra-master-opct-oci-assisted-periodic/1823146446296190976
```sh
$ oc get pods -n opct
NAME                                                               READY   STATUS       RESTARTS   AGE
sonobuoy                                                           1/1     Running      0          111m
sonobuoy-05-openshift-cluster-upgrade-job-15de00c8fa24452e         0/3     Init:Error   0          111m …
```

OPCT-300: fix kubernetes service URL

---

pkg/retrieve/retrieve.go
pkg/run/run.go
pkg/status/printer.go
pkg/status/printer_test.go
pkg/status/status.go

The changes in the status summary loop, increases the verbosity by collecting the pod status when there is no information from aggregator. It can help to quickly detect failures in the environment.
Example of "silent failure" happening in a [CI job][1]:
~~~
Tue, 13 Aug 2024 03:43:52 UTC|2h2m50.961758625s> Global Status: running
JOB_NAME | STATUS | RESULTS | PROGRESS | MESSAGE
05-openshift-cluster-upgrade | running | | | waiting for jobs initialization=PodStatus(Failed)
10-openshift-kube-conformance | running | | | waiting for jobs initialization=PodStatus(Failed)
20-openshift-conformance-validated | running | | | waiting for jobs initialization=PodStatus(Failed)
80-openshift-tests-replay | running | | | waiting for jobs initialization=PodStatus(Failed)
99-openshift-artifacts-collector | …

OPCT-257: Increase verbosity on status loop to detect failures

---

pkg/retrieve/retrieve.go
pkg/run/run.go
pkg/status/cmd.go
pkg/status/printer.go
pkg/status/printer_test.go
pkg/status/status.go
pkg/status/utils.go
pkg/status/utils_test.go
pkg/types.go

The command initialization must have minimal to no external dependencies to create the command.
Currently OPCT commands have been with some dependencies to initialize the `Run` command, which isn't the best practice.
The #118 introduced a new external dependency requiring a live cluster when the cobra is creating and initializing the command (without triggering it), which isn't expected nor desired, as OPCT tool provides many capabilities to operate without access to O/K API, such as `report` command which is affected raising an error after #118:
~~~
$ opct-devel report --save-to res opct_202408131745_9dd0adf1-df49-44fd-ae32-9c2ace0946c9.tar.gz --log-level=debug
ERRO[0000] error creating clients: error creating sonobuoy rest helper: could not get api group resources: Get …

OPCT-257:  fix status cmd must not required clients to init command

---

docs/user.md

Fix matrix of compatibility of OPCT tested versions VS OpenShift/OKD version according to the v0.5+ OPCT release.

OPCT-257: Documentation: fix OCP matrix with v0.5+

---

.github/workflows/e2e.yaml

Fix URL for CI artifacts from public S3 Bucket to a restricted path exposed by CloudFront with selected artifacts used by Github Actions.

OPCT-00: CI - fix e2e artifacts URL

---

.github/workflows/e2e.yaml
internal/cleaner/cleaner.go
internal/cleaner/cleaner_test.go
pkg/cmd/adm/cleaner.go
pkg/cmd/adm/root.go
pkg/retrieve/retrieve.go

[OCPBUGS-46532](https://issues.redhat.com/browse/OCPBUGS-46532)
Plugin ref https://issues.redhat.com/browse/OCPBUGS-46369
https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/68
This PR introduce a cleaner engine to remove predefined, unexpected, data from artifacts on client side to prevent exposing it to shareable/public artifacts.

OCPBUGS-46532: clean data while collecting result archive

---

internal/report/slo.go

Fix documentation hyperlink to force the lower alphabetical values on rendered markdown pages - references/sections on https://redhat-openshift-ecosystem.github.io/opct/review/rules
This bug affects only report Web UI which points each SLO/Rule directly to the OPCT documentations:
https://issues.redhat.com/browse/OPCT-311

OPCT-311: fix(web-ui) - rule hyperlink must use rendered by docs

---

pkg/types.go

Blocked by:
- https://github.com/redhat-openshift-ecosystem/opct/pull/130
- https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/68
- https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/69
- https://github.com/redhat-openshift-ecosystem/opct/pull/128
- https://github.com/redhat-openshift-ecosystem/opct/pull/129
- https://github.com/redhat-openshift-ecosystem/opct/pull/134

OPCT-000: Bump to v0.5.1 to address bug fixes

---

docs/dev/arch-support.md
docs/dev/release.md
docs/guides/features/validating-arm-installations.md

Creating ARM64 support on OPCT validation environment, it is required to build/mirror multi-arch (amd64 and arm64) the following components:
- sonobuoy aggregator server/worker image
- plugin openshift-tests image (and dependencies)
- tools (base image) and dependencies (oc, jq, etc)
- must-gather-monitoring image
The build for those components are implemented in the PR https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/51
This PR bumps the Plugins image to use multi-arch payloads starting the next release (v0.5.0-alpha.3). The documentation is also provided with steps to create new builds and to quickly test in an ARM cluster, OCP on AWS with IPI.
Note: I am not updating `mkdocs.html` to prevent indexing new docs in the current documentation release. cc …

OPCT-270: Added arm64 instructions and multi-arch builds

---

docs/review/index.md
docs/review/rules.md
internal/report/slo.go

Fix typos and verbiage in the [rules document](https://redhat-openshift-ecosystem.github.io/opct/review/rules/). The markdown rules.md is generated automatically by `opct adm generate checks-rules`.
_Isolating changes from https://github.com/redhat-openshift-ecosystem/opct/pull/124_
**Which issue(s) this PR fixes**
**Checklist**

OPCT-263: docs/rules: fix typos/verbiage on SLO/Rules

---

.github/workflows/static-website.yml
.gitignore
Makefile
docs/requirements.txt

Nit: move the requirements.txt, which handles mkdocs build dependencies, to the docs directory.
_Isolating changes from https://github.com/redhat-openshift-ecosystem/opct/pull/124_
**Checklist**

OPCT-263: docs: move requirements to docs/ path

---

pkg/types.go

Update plugins release fixing security dependencies.
**Which issue(s) this PR fixes** :
https://issues.redhat.com/browse/SPLAT-2030
https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/actions/runs/13638099271
https://quay.io/repository/opct/plugin-openshift-tests?tab=tags
https://quay.io/repository/opct/plugin-artifacts-collector?tab=tags
https://quay.io/repository/opct/must-gather-monitoring?tab=tags
**Checklist**

SPLAT-2030: fixes: bump plugins to v0.5.2 fixing security alerts

---

docs/devel/docs.md

Moving the devel guides to a dedicated directory, introducing FAQs and enhancing the contribution guides, alogside development nuances and procedures targeting to decrease the time to onboard new contributions.
_Isolating changes from https://github.com/redhat-openshift-ecosystem/opct/pull/124_
**Checklist**

OPCT-263: docs/dev: enhance dev guides for v0.5

---

hack/image-mirror-sonobuoy/mirror.sh

Update the aggregator server mirror config to v0.57.3 to get the changes in #144, then:
`make image-mirror-sonobuoy`
And check the mirrored images to OPCT registry: https://quay.io/repository/opct/sonobuoy?tab=tags
https://issues.redhat.com/browse/SPLAT-2030
**Checklist**

OPCT-2030: mirror aggregator server/sonobuoy img v0.57.3

---

.github/workflows/pull-request.yaml

Ensure the `kind/?` label has been added to the pull requests to be classified when generating a new release. It may prevent the dev to backfill pull requests, or having unclassified PRs as the following example: 
https://github.com/redhat-openshift-ecosystem/opct/releases/tag/v0.5.2
**Which issue(s) this PR fixes** 
**Checklist**

NO-JIRA: CI - added step to force kind label in a PR

---

docs/guides/features/running-e2e.md

This guide describes how to run e2e outside of the static workflow provided by opct, using native toolings, such as sonobuoy wrapper, and openshift-tests.
_This PR decomposes changes from https://github.com/redhat-openshift-ecosystem/opct/pull/113_
**Which issue(s) this PR fixes**
**Checklist**

OPCT-263: docs: added guide to run e2e manually

---

docs/devel/byo-plugin.md
docs/guides/cluster-validation/installation-review.md

Review installation-review guide removing unnecessary etcd data which is
now addressed by a embedded/adm command.
_This PR decomposes changes from https://github.com/redhat-openshift-ecosystem/opct/pull/113_
Closes #113 
**Checklist**

OPCT-263: docs: review installation review guide removing etcd log

---

docs/guides/cluster-validation/installation-review.md
hack/generate-changelog.sh
mkdocs.yml

Changes:
- Fix documentation builder in the CD pipeline introduced by https://github.com/redhat-openshift-ecosystem/opct/pull/156[1] when the changelog generator parser was crashing while attempting to extract the PR ID from the squashed commit name.
- Re-add the generated changelog markdown page to a new section
- Fix type in the CLI reference URL
[1] https://github.com/redhat-openshift-ecosystem/opct/actions/runs/13708777894
Fixes #
**Checklist**

NO-JIRA: documentation fixes in the changelog CD pipeline

---

docs/guides/cluster-validation/index.md
pkg/run/run.go

Validation of the `opct` `machineconfigpool` has been failing.  It appears that this [change](https://github.com/openshift/machine-config-operator/commit/d260da67967aa3e30a50a2229c52059d49a6c360) revealed typos in https://github.com/redhat-openshift-ecosystem/opct/blob/9ddc26024dfbf3c0dba4dca305ecdac6cbe9d69f/pkg/run/run.go#L310-L311 related to trailing commas.  This change removes those commas.
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #
- OPCT-342
**Checklist**

OPCT-342: fix matchExpressions to remove trailing commas

---

docs/assets/output/_generate-outputs.sh
docs/assets/output/opct-adm-parse-junit.txt
docs/opct/adm/parse-junit.md
mkdocs.yml
pkg/api/junit.go
pkg/api/junit_test.go
pkg/cmd/adm/parsejunit.go
pkg/cmd/adm/root.go

Introduce a command to parse the JUnit files produced by e2e tests.
This is a helper when running `openshift-tests` manually, it will provide quickly access to the results without struggling with parsing the XML file with `xq`.
~~~
$ opct-devel adm parse-junit failed_tests_rerun/results/junit_e2e__20240827-213043.xml 
Summary:
- File: failed_tests_rerun/results/junit_e2e__20240827-213043.xml
- Total: 19
- Pass: 9
- Skipped: 0
- Failures: 10
JUnit Attributes:
- XMLName: { testsuite}
- Name: openshift-tests
- Tests: 19
- Skipped: 0
- Failures: 10
- Time: 2568
- Property: {TestVersion 4.14.0-202310201027.p0.g948001a.assembly.stream-948001a}
#> Passed tests (9): 
[sig-instrumentation] MetricsGrabber should grab all metrics slis from API server. [Suite:openshift/conformance/parallel] …

OPCT-304: cmd: adm parser-junit

---

docs/devel/guide.md
pkg/cmd/adm/e2ed/controller.go
pkg/cmd/adm/e2ed/root.go
pkg/cmd/adm/e2ed/taintNode.go
pkg/destroy/destroy.go
pkg/run/run.go
pkg/types.go

This change is proposing a controller to watch the e2e pods failed to schedule, mutating those to apply the OPCT  dedicated toleration, targeting to prevent false-positive failures in the conformance results due the dedicated node introduced as required by OPCT.
The controller is started by a command `adm e2e-dedicated controller`, distributed with the same image of `opct`. The deployment will be created in `opct` namespace when the command `run` is executed. The destroy flow will remove all resources in `opct` namespace, not requiring a dedicated logic to remove the controller deployment.
Rehearsal Tests: https://github.com/openshift/release/pull/62503
Done checklist:
- This change resolves all e2e tests choosing randomly workers node. We've …

OPCT-332: added a controller to mutate e2e pods failed to schedule

---

.github/workflows/e2e.yaml
internal/cleaner/cleaner.go
pkg/cmd/adm/cleaner.go
pkg/cmd/adm/parsemetrics.go

This PR introduces:
- Enhance the cleaner scanner to remove unused files by patterns when collecting the results from the server - client-side phase.
- Remove the weight, and unused, namespaced files `/packages.operators.coreos.com_v1_packagemanifests.json`, objects collected by sonobuoy aggregator. One file will stayed in the archive just for conference. This action will reduce the final archive file to almost 1/3 (from ~160 MiB to ~60MiB)
**Which issue(s) this PR fixes** :
https://issues.redhat.com/browse/OPCT-339
https://issues.redhat.com/browse/OPCT-340
**Checklist**

OPCT-339: cleaner: enhance archive removing unused objects

---

pkg/types.go

Bump plugins to v0.6.0-alpha.1 version. Build pipeline is publishing the image https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/actions/runs/13864670936
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #
**Checklist**

OPCT-348: bump plugins for v0.6.0-alpha.1

---

docs/guides/cluster-validation/index.md

Updating "Validation User Guide" to ensure users are following valid installation paths, this is aligned with VCSP program goals to use Platform Type External across all supported paths.
[OPCT-349](https://issues.redhat.com/browse/OPCT-349)
**Checklist**

OPCT-349: docs: update instructions with valid OCP platform types for VCSP

---

data/templates/plugins/openshift-artifacts-collector.yaml

Disable kube-burner in stable releases to prevent CI issues.
Kube-burner need to be tuned to prevent long-running jobs. See the following jobs increasing almost one hour waiting for the 1/3 kube-burner job: 
[ci/rehearse/periodic-ci-openshift-release-master-nightly-4.18-opct-external-aws-ccm](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/63503/rehearse-63503-periodic-ci-openshift-release-master-nightly-4.18-opct-external-aws-ccm/1909362302688169984)
ci/rehearse/periodic-ci-openshift-release-master-nightly-4.18-opct-external-aws-ccm — Job failed.                     BaseSHA:8b7eee7e759de990b51d51bbfc811f0ec26c8916
[ci/rehearse/periodic-ci-redhat-openshift-ecosystem-opct-main-4.16-platform-external-vsphere-u …

OPCT-326: disable kube-burner fixing long-running v0.6

---

docs/devel/create-cluster-external.md
mkdocs.yml

Add devel document fragment to be used as a helper to deploy platform external clusters (reusing from CI scripts) to manipulate opct and test tooling.
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #
**Checklist**

NO-JIRA: docs: devel: create platform external cluster
